import React from 'react';
import Layout from '../components/Layout';
import styles from '../styles/Legal.module.css';

export default function RiskDisclosure() {
  return (
    <Layout title="Risk Disclosure Statement | OptiWise">
      <div className={styles.container}>
        <main className={styles.main}>
          <h1 className={styles.title}>Risk Disclosure Statement</h1>
          
          <div className={styles.content}>
            <section className={styles.section}>
              <h2>Introduction</h2>
              <p>
                This Risk Disclosure Statement is provided to you by OptiWise in accordance with industry best practices. It outlines the general nature of the risks associated with using our services and tools for investment decision-making. This statement does not disclose all the risks and other significant aspects of trading in financial instruments. You should ensure that your decision to use our services is made with a full understanding of the risks involved.
              </p>
            </section>

            <section className={styles.section}>
              <h2>General Investment Risks</h2>
              <p>
                All forms of investment carry risks. The value of your investments can go down as well as up, and you may get back less than you initially invested. Past performance is not indicative of future results. The risk of loss in trading can be substantial, and you should be aware that you might sustain losses in excess of your initial investment.
              </p>
            </section>

            <section className={styles.section}>
              <h2>Market Volatility</h2>
              <p>
                Financial markets can be highly volatile and prices of financial instruments can fluctuate rapidly based on unforeseen events or changes in conditions, none of which can be controlled by us. Market volatility can significantly impact the prices of the securities you are considering and can lead to substantial losses in a short period of time.
              </p>
            </section>

            <section className={styles.section}>
              <h2>Technical Analysis Limitations</h2>
              <p>
                OptiWise provides tools for technical analysis and portfolio optimization. However, technical analysis has inherent limitations and is not guaranteed to predict future price movements accurately. The signals generated by our tools should be considered as one of many factors in your investment decision-making process.
              </p>
            </section>

            <section className={styles.section}>
              <h2>No Guaranteed Returns</h2>
              <p>
                OptiWise does not guarantee any specific outcome, return on investment, or performance level. Any examples, forecasts, or hypothetical results presented by our tools are purely illustrative and do not represent actual results or guarantees of future performance.
              </p>
            </section>

            <section className={styles.section}>
              <h2>Technology Risks</h2>
              <p>
                The use of OptiWise's platform involves risks associated with online systems, including but not limited to software failures, hardware failures, connectivity issues, and potential security breaches. These technical issues could affect your ability to use our services or the accuracy of the information provided.
              </p>
            </section>

            <section className={styles.section}>
              <h2>Personal Responsibility</h2>
              <p>
                You are solely responsible for your investment decisions. OptiWise provides tools and information, but the ultimate decision to make any specific investment should be made by you based on your own research, financial situation, investment objectives, and risk tolerance.
              </p>
            </section>

            <section className={styles.section}>
              <h2>Seek Professional Advice</h2>
              <p>
                We strongly recommend that you seek advice from an independent financial advisor if you have any doubts about the suitability of an investment. Nothing in our service constitutes legal, financial, or investment advice, and we do not provide personalized investment recommendations.
              </p>
            </section>

            <section className={styles.section}>
              <h2>Changes to Risk Disclosure Statement</h2>
              <p>
                OptiWise reserves the right to update this Risk Disclosure Statement at any time. We will notify users of any material changes. Your continued use of our services following such changes constitutes your acceptance of the revised Risk Disclosure Statement.
              </p>
            </section>
          </div>
        </main>
      </div>
    </Layout>
  );
}
